# Generated by Django 5.1.4 on 2025-11-23 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PhotoAnalyzer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="context",
            field=models.TextField(blank=True, null=True),
        ),
    ]
