# Generated by Django 5.1.4 on 2025-11-23 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("PhotoAnalyzer", "0002_photo_context"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photo",
            name="context",
        ),
    ]
